# Generated by Django 4.2.6 on 2025-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='analyser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='finaliser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='mot_cle',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
