# Generated by Django 4.2.6 on 2025-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personne_remove_article_category_article_analyser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mot_cle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
