# Generated by Django 4.2.6 on 2025-01-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_date_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mot_cle',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
